spring:
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: false

  sql:
    init:
      mode: always

  datasource:
    url: jdbc:h2:mem:proposaldb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    defer-datasource-initialization: false
    database-platform: org.hibernate.dialect.H2Dialect

server:
  port: 8080